task7project/movie_project/movie_app/urls.py
from django.urls import path
from . import views
app_name='movie_app'

urlpatterns=[
    path('',views.index,name='index'),
    path('movie/<int:movieid>/',views.detail,name='detail'),
    path('add/',views.add_movies,name='add_movies'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete')

]

task7project/movie_project/movie_project/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movie_app.urls'))
]
if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL,
                         document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL,
                         document_root=settings.MEDIA_ROOT)

task7project/movie_project/movie_app/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    name=models.CharField(max_length=200)
    desc=models.TextField()
    year=models.IntegerField()
    image=models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

task7project/movie_project/movie_app/forms.py
from django import forms
from .models import Movie

class MovieForm(forms.ModelForm):
    class Meta:
        model=Movie
        fields=['name','desc','year','image']

task7project/movie_project/movie_app/views.py
from django.shortcuts import render, redirect

# Create your views here.
from django.http import HttpResponse
from .models import Movie
from .forms import MovieForm

def index(request):
    movie=Movie.objects.all()
    context={'movielist':movie}

    return render(request,"index.html",context)
def detail(request,movieid=id):
    movie=Movie.objects.get(id=movieid)
    return render(request,"detail.html",{'movie':movie})

def add_movies(request):
    if request.method=='POST':
        name=request.POST.get('name')
        desc1=request.POST.get('desc')
        year1=request.POST.get('year')
        image1=request.FILES['image']
        movie1=Movie(name=name,desc=desc1,year=year1,image=image1)
        movie1.save()
    return render(request, "add.html")

def update(request,id):
    movie2=Movie.objects.get(id=id)
    form1=MovieForm(request.POST or None,request.FILES,instance=movie2)
    if form1.is_valid():
        form1.save()
        return redirect('/')
    return render(request,"edit.html",{'form':form1,'movie':movie2})
def delete(request,id):
    if request.method=="POST":
        movie=Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,"delete.html")

task7project/movie_project/templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="Enter the Movie Name">
    <input type="text" name="desc" placeholder="Enter the Movie Description">
    <input type="text" name="year" placeholder="Enter the year">
    <input type="file" name="image">
    <input type="submit">
</form>
{% endblock %}

task7project/movie_project/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
    Online Movie Store
  </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

task7project/movie_project/templates/delete.html
<form method="post">
    {% csrf_token %}
    Are ypu sure you want to delete this movie?
    <input type="submit">

</form>

task7project/movie_project/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{movie.image.url}}" width="250" height="250">
        </div>
        <div class="col-md-6">
           <h2>{{movie.name}}</h2>
             <h4>{{movie.desc}}</h4>
            <h5>{{movie.year}}</h5>
         <a class="btn btn-warning" href="{% url 'movie_app:update' movie.id %}">Update</a>
        <a class="btn btn-danger" href="{% url 'movie_app:delete' movie.id %}">Delete</a>
        </div>
    </div>
</div>


{% endblock %}

task7project/movie_project/templates/edit.html
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>

task7project/movie_project/templates/index.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        {% for i in movielist %}
        <div class="col-md-3">
            <div class="card" style="width: 18rem;">
            <img class="card-img-top" src="{{i.image.url}}" alt="Card image cap" width="250" height="250">
            <div class="card-body">
           <h5 class="card-title">{{i.name}}</h5>
           <p class="card-text">{{i.desc}}</p>
            <a href="{% url 'movie_app:detail' i.id %}" class="btn btn-primary">View Details</a>
  </div>
</div>
        </div>
        {% endfor %}
    </div>
</div>


{% endblock %}